name: Checks
on:
  push:
  pull_request:
jobs:
  scalafix:
    name: Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'

      - run: sbt scalafixCheckAll

  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'

      - run: sbt "scalafmtCheckAll; scalafmtSbtCheck"
