name: Checks
on:
  push:
  pull_request:
jobs:
  scalafix:
    name: Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'

      - name: Scalafix
        run: sbt scalafixCheckAll

      - name: Scalafmt
        run: sbt scalafmtCheckAll

